services:
  backend:
    build:
      context: ./backend
    expose:
      - "5000"  # Используем expose вместо ports для внутреннего доступа
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - PYTHONUNBUFFERED=1
    depends_on:
      database:
        condition: service_healthy
    command: python app/app.py
    volumes:    # добавление в контейнер внешнюю папку которая синхронизированна с гугль-драйвом через
      - ./backend/suunto-trainings:/app/suunto-trainings    # rclone - дополнительно добавлена в контейнер (костыль!)
      - ./logs:/app/logs   # проброс папки для логов

  database:
    build:
      context: ./database
    expose:
      - "3306"  # Только для внутреннего доступа
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80" # тут внешний доступ
    depends_on:
      - backend
  